controller_manager:
  ros__parameters:
  
    update_rate: 10

    ndi:
      type: rigid_pose_broadcaster/RigidPoseBroadcaster

ndi:
  ros__parameters:
    state_publish_rate: 10
    sensor_names:
      - zframe
      - handle
      - template
      - needle
    sensor_ids:
      - 01
      - 02
      - 03
      - 04
    world_frame: aurora

